---
- hosts: egeeio01
  tasks:
    - name: Update 7DaysToDie Server
      shell: /bin/bash /home/egee/7dayz/sdtdserver update
      register: stdout
    - debug: var=stdout
    - name: Update Rust Server
      shell: docker exec gscrust_rust-server_1 update
      register: stdout
    - debug: var=stdout
